spring:
  jms:
      template:
        default-destination: default.message.queue
  activemq:
    broker-url: tcp://192.168.2.113:61616
    user: admin
    password: admin
  mail:
    host: 192.168.2.181
    #port: 25
    username: xiaotang@9f0.net
    password: 123456
    properties:
      mail:
        smtp:
          auth: true
          timeout: 30000
          # MailAuthenticationException: Authentication failed
          ##starttls:
          ##  enable: false
          ##  required: false